# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d21f23c8734a26e2a349f389625211eac2eeb7f390dd7baf0453454e64493247937571d93bde8ff2193f277841220f2d7a85ab4628f92a525ab81d5eebf0063

test:
  secret_key_base: 2de9d14fd997547119769ca4a01b0b2ed8d8c0121aedc5606c9c03b15c2a9d25400b4d930ebb3fd7b72c52995aabf96ea9f42178d24399ead52f0457c15ac524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
